version: 2.1

orbs:
  aws-eks: circleci/aws-eks@0.2.0
  aws-ecr: circleci/aws-ecr@3.1.0
  kubernetes: circleci/kubernetes@0.3.0

jobs:
  deploy-application:
    executor: aws-eks/python3
    parameters:
      cluster-name:
        description: |
          eks-cluster
        type: string
      docker-image-name:
        description: |
          webpagetest/server:latest
        type: string
      version-info:
        description: |
          App Test
        type: string
      aws-region:
        description: |
          AWS region
        type: string
        default: "us-east-1"
    # steps:
    #   - checkout
    #   - run:
    #       name: Create deployment manifest
    #       command: |
    #         BUILD_DATE=$(date '+%Y%m%d%H%M%S')
    #         cat ../app/webtest-zup.yaml |\
    #            sed "s|DOCKER_IMAGE_NAME|<< webpagetest/server:latest >>|\
    #             g;s|BUILD_DATE_VALUE|$BUILD_DATE|g;s|VERSION_INFO_VALUE|\
    #             << parameters.version-info >>|g" > ../app/webtest-zup.yaml
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.cluster-name >>
          install-kubectl: true
          aws-region: << parameters.aws-region >>
      - kubernetes/create-or-update-resource:
          resource-file-path: "../app/webtest-zup.yaml"
          get-rollout-status: true
      - kubernetes/create-or-update-resource:
          resource-file-path: "../app/webtest-zup.yaml"

workflows:
  deployment:
    jobs:
      - deploy-application:
          cluster-name: cks-cluster
          aws-region: $AWS_DEFAULT_REGION
          docker-image-name: "webpagetest/server:latest"
          version-info: "${CIRCLE_SHA1}"
